### ISSUE TITLE
Allow for an empty contract in ERC20Transfers function

### ISSUE THREAD

**Issue by BenKnigge** [nanmu42/etherscan-api#11]
pull request #10 

This would allow for an empty string pointer to be passed in to ERC20Transfers
resulting in the parameter of the contract address being omitted from the underlying api call.

The result being all coin transfers being returned instead of a list filtered by contract address.

**Comment by nanmu42** [comment]
Have you tried passing `nil` to `contractAddress`? I think that would do what you need.

**Comment by BenKnigge** [comment]
yes, nil seems to work
