### ISSUE TITLE
ERC721721物品交易记录查询

### ISSUE THREAD

**Issue by hwck** [nanmu42/etherscan-api#13]
能否提供一个查询ERC721物品的交易记录
类似下面这个 查询 tokenId=981521的所有交易记录
[https://etherscan.io/token/0x06012c8cf97bead5deae237070f9587f8e7a266d?a=981521&tdsourcetag=s_pcqq_aiomsg](https://etherscan.io/token/0x06012c8cf97bead5deae237070f9587f8e7a266d?a=981521&tdsourcetag=s_pcqq_aiomsg)

**Comment by nanmu42** [comment]
这个库是Etherscan的API的Go绑定，实现的内容不会超出API所提供的内容。

如果Etherscan的API提供了ERC721的相关查询功能，我会考虑跟进。（据我所知，目前还没有）

对于你的需求，我可以提供协助（有偿），你可以邮件联系我。
