### ISSUE TITLE
NIL parameters pass to rpc-call

### ISSUE THREAD

**Issue by engenegr** [nanmu42/etherscan-api#3]
They are not pass, if the code in helper.go change to:
```
// compose adds input to param, whose key is tag
// if input is nil, compose is a no-op.
func compose(param map[string]interface{}, tag string, input interface{}) {
	if  reflect.ValueOf(input).IsNil() {
		return
	}
	param[tag] = input
}
```

**Comment by nanmu42** [comment]
Could you elaborate on this?

**Comment by nanmu42** [comment]
I see the current version working as expected.

Is there a specific reason for this modification?

**Comment by engenegr** [comment]
Hey,
Maybe I'm an inexperienced coder in Golang and did something wrong but

`ERC20TxList, err := client.ERC20Transfers( nil, &watchAddress, nil, nil, 0, 0)`

Didn't work.
The reason was this piece pass nil further:

```
	if input == nil {
		return
	}
```
The problem initially happened with startBlock/endBlock since you commented about them that they could be equal to nil or something and I later found in etherscan.io documentation about it. I only found a way after that because I was too lazy to write a code which figures out contract addresses.

**Comment by engenegr** [comment]
I'm very sorry, the header of an issue could misguide you.

**Comment by engenegr** [comment]
@nanmu42 I see a link to Golang FAQ. I investigated Golang types a little bit and realized that the problem is in non-nil type value. Do you know another solution to this without reflect?

**Comment by nanmu42** [comment]
Thank you for finding this bug. :beers: 

The problem should be solved in `v1.0.2`. You may close this issue after confirming it is working.

Yes, there is another way, but less DRY -- check for nil in every function like `ERC20Transfers()`, so long as it is not passed in an interface, `if a == nil` should still work as expected.

**Comment by nanmu42** [comment]
You are very kind. :D

**Comment by nanmu42** [comment]
I am closing this.

Feel free to reopen this issue if the bug persist.
