### ISSUE TITLE
gas-tracker api

### ISSUE THREAD

**Issue by jxlwqq** [nanmu42/etherscan-api#70]
https://docs.etherscan.io/api-endpoints/gas-tracker

可否支持 gas-tracker 系列接口

**Comment by francisbayode6** [comment]
What kind of help mate?

**Comment by nanmu42** [comment]
I am not currently use this package, so it would be nice if someone interested is willing to implement this feature.

**Comment by nanmu42** [comment]
Closed via #74 .

A new release is coming.
