### ISSUE TITLE
Is there a way to get only income transaction to an address using etherscan a.k.a this library?

### ISSUE THREAD

**Issue by oussamarouabah** [nanmu42/etherscan-api#77]
Hey all,

I am trying to use this library to get some information from the etherscan APIs specifically Income transaction to an address on the blockchain is there a way to filter these transactions or to get only these transactions using API calls?

Thanks.

**Comment by huetterma** [comment]
Hey,
@oussamarouabah you would need to call `ERC20Transfers` with the address being your address. Further a check if the exposed `To` field is your address, else it is an outgoing transaction.

So, yes it is possible.
